// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models;

public partial class Dokument
{
    public int DokumentId { get; set; }

    public int ProjektId { get; set; }

    public string Naslov { get; set; }

    [Display(Name = "Sadržaj")]
    public string Sadrzaj { get; set; }

    public int KategorijaDokumentaId { get; set; }

    public virtual KategorijaDokumenta KategorijaDokumenta { get; set; }

    public virtual Projekt Projekt { get; set; }
}