// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models;

public partial class KategorijaDokumenta
{
    public int KategorijaDokumentaId { get; set; }

    [Display(Name = "Naziv")]
    public string NazivKategorijeDokumenta { get; set; }

    public virtual ICollection<Dokument> Dokument { get; set; } = new List<Dokument>();
}