// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class PosaoReportModel
{
    public int Id { get; set; }

    public string Naziv { get; set; }

    public String OcekivaniPocetak { get; set; }

    public String OcekivaniZavrsetak { get; set; }

    public int Budzet { get; set; }

    public virtual Projekt Projekt { get; set; }

    public virtual VrstaPosla VrstaPosla { get; set; }

    public static PosaoReportModel FromPosao(Posao posao)
    {
        return new PosaoReportModel
        {
            Id = posao.Id,
            Projekt = posao.Projekt,
            Naziv = posao.Naziv,
            OcekivaniPocetak = posao.OcekivaniPocetak.ToString("dd.M.yyyy"),
            OcekivaniZavrsetak = posao.OcekivaniZavrsetak.ToString("dd.M.yyyy"),
            Budzet = posao.Budzet,
            VrstaPosla = posao.VrstaPosla
        };
    }
}