// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models;

public partial class Projekt
{
    public int IdProjekt { get; set; }

    [Display(Name = "Početak projekta")]
    public DateTime PocetakProjekta { get; set; }

    [Display(Name = "Kraj projekta")]
    public DateTime KrajProjekta { get; set; }

    [Display(Name = "Naziv projekta")]
    public string ImeProjekta { get; set; }

    public string Oznaka { get; set; }

    public string Opis { get; set; }

    [Display(Name = "Račun")]
    public int IdRacuna { get; set; }

    [Display(Name = "Vrsta projekta")]
    public int IdVrstaProjekta { get; set; }

    public virtual ICollection<Dokument> Dokument { get; set; } = new List<Dokument>();

    public virtual Racun Racun { get; set; }

    public virtual VrstaProjekta VrstaProjekta { get; set; }

    public virtual ICollection<Posao> Posao { get; set; } = new List<Posao>();

    public virtual ICollection<UlogaNaProjektu> UlogaNaProjektu { get; set; } = new List<UlogaNaProjektu>();
}