// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Suradnik
{
    public int Id { get; set; }

    public string Naziv { get; set; }

    public string Oib { get; set; }

    public string Adresa { get; set; }

    public string PostanskiBroj { get; set; }

    public string Grad { get; set; }

    public int VrstaSuradnikaId { get; set; }

    public int PosaoId { get; set; }

    public virtual Posao Posao { get; set; }

    public virtual VrstaSuradnika VrstaSuradnika { get; set; }
}