// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Transakcija
{
    public int Idtransakcije { get; set; }

    public int Idracuna { get; set; }

    public int Iznos { get; set; }

    public int IdvrstaTransakcije { get; set; }

    public string VanjskiIban { get; set; }

    public int? UnutarnjiIdRacuna { get; set; }

    public string SmjerTransakcije { get; set; }

    public virtual Racun Racun { get; set; }

    public virtual VrstaTransakcije VrstaTransakcije { get; set; }

    public virtual Racun UnutarnjiRacun { get; set; }
}