// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

/// <summary>
/// Djelomična klasa koja predstavlja ulogu.
/// </summary>
public partial class Uloga
{
    /// <summary>
    /// Jedinstveni identifikator uloge.
    /// </summary>
    public int IdUloga { get; set; }

    /// <summary>
    /// Naziv uloge.
    /// </summary>
    public string NazivUloge { get; set; }

    /// <summary>
    /// Kolekcija uloga na projektima koje pripadaju ovoj ulozi.
    /// </summary>
    public virtual ICollection<UlogaNaProjektu> UlogaNaProjektu { get; set; } = new List<UlogaNaProjektu>();
}