// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

/// <summary>
/// Djelomična klasa koja predstavlja ulogu na projektu.
/// </summary>
public partial class UlogaNaProjektu
{
    /// <summary>
    /// Jedinstveni identifikator projekta.
    /// </summary>
    public int IdProjekt { get; set; }

    /// <summary>
    /// Jedinstveni identifikator uloge.
    /// </summary>
    public int IdUloga { get; set; }

    /// <summary>
    /// Jedinstveni identifikator osobe.
    /// </summary>
    public int IdOsoba { get; set; }

    /// <summary>
    /// Jedinstveni identifikator.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Osoba koja ima ulogu na projektu.
    /// </summary>
    public virtual Osoba Osoba { get; set; }

    /// <summary>
    /// Projekt na kojem je definirana uloga.
    /// </summary>
    public virtual Projekt Projekt { get; set; }

    /// <summary>
    /// Uloga koja je definirana na projektu.
    /// </summary>
    public virtual Uloga Uloga { get; set; }
}