// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

/// <summary>
/// Djelomična klasa koja predstavlja vrstu zadatka.
/// </summary>
public partial class VrstaZadatka
{
    /// <summary>
    /// Jedinstveni identifikator vrste zadatka.
    /// </summary>
    public int IdVrstaZdtk { get; set; }

    /// <summary>
    /// Naziv vrste zadatka.
    /// </summary>
    public string NazivVrsteZdtk { get; set; }

    /// <summary>
    /// Zadaci koji pripadaju ovoj vrsti zadatka.
    /// </summary>
    public virtual ICollection<Zadatak> Zadatak { get; set; } = new List<Zadatak>();
}