// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class VrstaSuradnika
{
    public int IdVrstaSuradnika { get; set; }

    public string Naziv { get; set; }

    public string Opis { get; set; }

    public virtual ICollection<Suradnik> Suradnik { get; set; } = new List<Suradnik>();
}