// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

/// <summary>
/// Djelomična klasa koja predstavlja zadatak.
/// </summary>
public partial class Zadatak
{
    /// <summary>
    /// Jedinstveni identifikator zadatka.
    /// </summary>
    public int IdZadatak { get; set; }

    /// <summary>
    /// Vrijeme isporuke zadatka.
    /// </summary>
    public DateTime VrijemeIsporuke { get; set; }

    /// <summary>
    /// Stupanj dovršenosti zadatka.
    /// </summary>
    public int StupanjDovrsenosti { get; set; }

    /// <summary>
    /// Prioritetnost zadatka.
    /// </summary>
    public string Prioritetnost { get; set; }

    /// <summary>
    /// Jedinstveni identifikator osobe zadužene za zadatak.
    /// </summary>
    public int IdOsoba { get; set; }

    /// <summary>
    /// Jedinstveni identifikator vrste zadatka.
    /// </summary>
    public int IdVrstaZdtk { get; set; }

    /// <summary>
    /// Naziv zadatka.
    /// </summary>
    public string Naziv { get; set; }

    /// <summary>
    /// Jedinstveni identifikator zahtjeva.
    /// </summary>
    public int? IdZahtjev { get; set; }

    /// <summary>
    /// Osoba zadužena za zadatak.
    /// </summary>
    public virtual Osoba Osoba { get; set; }

    /// <summary>
    /// Vrsta zadatka.
    /// </summary>
    public virtual VrstaZadatka VrstaZadatka { get; set; }

    /// <summary>
    /// Zahtjev kojem zadatak pripada.
    /// </summary>
    public virtual Zahtjev Zahtjev { get; set; }

    /// <summary>
    /// Osobe zadužene za izvršavanje zadatka.
    /// </summary>
    public virtual ICollection<ZaduzenaOsoba> ZaduzenaOsoba { get; set; } = new List<ZaduzenaOsoba>();
}