// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class ZaduzenaOsoba
{
    public int IdOsoba { get; set; }

    public int IdZadatak { get; set; }

    public int IdZaduzenja { get; set; }

    public virtual Osoba Osoba { get; set; }

    public virtual Zadatak Zadatak { get; set; }
}